version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: siacom_db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --log-bin-trust-function-creators=1
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      TZ: "${TZ:-UTC}"
    volumes:
      - db_data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql:ro
    ports:
      - "${DB_PORT}:3306"
    networks:
      - backend
      - admin_ph
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 20s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: "${DB_ROOT_PASSWORD}"
      UPLOAD_LIMIT: 64M
    ports:
      - "8080:80"
    networks:
      - admin_ph

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: siacom_api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      SECRET_KEY: "${SECRET_KEY}"
      TZ: "${TZ:-UTC}"
    ports:
      - "8000:8000"
    networks:
      - backend
    volumes:
      - ./backend:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  # 🔧 Modo DESARROLLO del frontend (Vite)
  frontend-dev:
    image: node:22-alpine
    container_name: siacom_frontend_dev
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: ["sh", "-c", "npm install && npm run dev -- --host 0.0.0.0"]
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - frontend

  # 🏗️ Modo PRODUCCIÓN (compilado y servido por Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: siacom_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - frontend

volumes:
  db_data:

networks:
  backend:
  admin_ph:
  frontend: